### ISSUE TITLE
Errors when upload firmware.

### ISSUE THREAD

**Issue by onlize** [marthocoo/GarHAge#1]
This is the first time ever I am trying to upload firmware to NodeMCU ESP8266. I use ESPlorer. I do not believe that this is right. I use your code, just changed IP addresses and passwords. What should I do to fix?
`
NodeMCU 0.9.6 build 20150704  powered by Lua 5.1.4
lua: cannot open init.lua
> // MQTT Garage Door Controller
stdin:1: unexpected symbol near '/'
> #include <ESP8266WiFi.h>
stdin:1: unexpected symbol near '#'
> #include <PubSubClient.h>
stdin:1: unexpected symbol near '#'
> /*
stdin:1: unexpected symbol near '/'
> * Start of user-configurable parameters
stdin:1: unexpected symbol near '*'
> */
stdin:1: unexpected symbol near '*'
> 
> // Wifi details
stdin:1: unexpected symbol near '/'
> const char* ssid = "@secretssid";
stdin:1: '=' expected near 'char'
> const char* password = "@secretpassword";
stdin:1: '=' expected near 'char'
> 
> // Static IP details
stdin:1: unexpected symbol near '/'
> // Set static_ip to "static" to use ip/gateway/subnet parameters below
stdin:1: unexpected symbol near '/'
> // Set static_ip to "dhcp" to obtain ip address via DHCP and ignore ip/gateway/subnet parameters
stdin:1: unexpected symbol near '/'
> const char* static_ip = "dhcp";
stdin:1: '=' expected near 'char'
> IPAddress ip(192,168,1,100);
stdin:1: '=' expected near 'ip'
> IPAddress gateway(192,168,1,1);
stdin:1: '=' expected near 'gateway'
> IPAddress subnet(255,255,255,0);
stdin:1: '=' expected near 'subnet'
> 
> // MQTT server details
stdin:1: unexpected symbol near '/'const char* mqtt_server = "@secretip";
stdin:1: '=' expected near 'char'
> const char* mqtt_clientId = "garage";
stdin:1: '=' expected near 'char'
> const char* mqtt_username = "@secretusername";
stdin:1: '=' expected near 'char'
> const char* mqtt_password = "@secretpassword";
stdin:1: '=' expected near 'char'
> 
> // MQTT topic details
stdin:1: unexpected symbol near '/'
> const char* mqtt_action_topic = "garage/action";
stdin:1: '=' expected near 'char'
> const char* mqtt_status_topic = "garage/status";
stdin:1: '=' expected near 'char'
> 
> // GPIO pin details
stdin:1: unexpected symbol near '/'
> int openPin = 4;
stdin:1: '=' expected near 'openPin'
> int closePin = 4;
stdin:1: '=' expected near 'closePin'
> int stopPin = 5;
stdin:1: '=' expected near 'stopPin'
> int statusPin = 14;
stdin:1: '=' expected near 'statusPin'
> 
> /*
stdin:1: unexpected symbol near '/'
> * End of user-configurable parameters
stdin:1: unexpected symbol near '*'
> */
stdin:1: unexpected symbol near '*'
> 
> int lastStatusValue = 0;
stdin:1: '=' expected near 'lastStatusValue'
> int currentStatusValue;
stdin:1: '=' expected near 'currentStatusValue'
> 
> 
> WiFiClient espClient;
stdin:1: '=' expected near 'espClient'
> PubSubClient client(espClient);
stdin:1: '=' expected near 'client'
> 
> // Wifi setup function
stdin:1: unexpected symbol near '/'
> void setup_wifi() {
stdin:1: '=' expected near 'setup_wifi'
> delay(10);
stdin:1: attempt to call global 'delay' (a nil value)
> Serial.println();
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.print("Connecting to ");
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.println(ssid);
stdin:1: attempt to index global 'Serial' (a nil value)
> 
> WiFi.begin(ssid, password);
stdin:1: attempt to index global 'WiFi' (a nil value)
> 
> if (static_ip == "static") {
>> WiFi.config(ip, gateway, subnet);
>> }
>> 
>> while (WiFi.status() != WL_CONNECTED) {
stdin:4: 'then' expected near 'while'
> delay(500);
stdin:1: attempt to call global 'delay' (a nil value)
> Serial.print(".");
stdin:1: attempt to index global 'Serial' (a nil value)
> }
stdin:1: unexpected symbol near '}'
> 
> Serial.println("");
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.println("WiFi connected");
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.println("IP address: ");
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.println(WiFi.localIP());
stdin:1: attempt to index global 'Serial' (a nil value)
> }
stdin:1: unexpected symbol near '}'
> 
> // Callback when MQTT message is received
stdin:1: unexpected symbol near '/'
> void callback(char* topic, byte* payload, unsigned int length) {
stdin:1: '=' expected near 'callback'
> Serial.print("Message arrived [");
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.print(topic);
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.print("] ");
stdin:1: attempt to index global 'Serial' (a nil value)
> 
> for (int i = 0; i < length; i++) {
stdin:1: '<name>' expected near '('
> Serial.print((char)payload[i]);
stdin:1: ')' expected near 'payload'
> }
stdin:1: unexpected symbol near '}'
> Serial.println();
stdin:1: attempt to index global 'Serial' (a nil value)
> 
> payload[length] = '\0';
stdin:1: attempt to index global 'payload' (a nil value)
> String payloadToProcess = (char*)payload;
stdin:1: '=' expected near 'payloadToProcess'
> Serial.print("Action payload is ");
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.print(payloadToProcess);
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.println(".");
stdin:1: attempt to index global 'Serial' (a nil value)
> triggerDoorAction(payloadToProcess);
stdin:1: attempt to call global 'triggerDoorAction' (a nil value)
> }
stdin:1: unexpected symbol near '}'
> 
> // Function that runs in loop() to check door status (open/closed) and publish changes
stdin:1: unexpected symbol near '/'
> void check_door_status() {
stdin:1: '=' expected near 'check_door_status'
> currentStatusValue = digitalRead(statusPin);
stdin:1: attempt to call global 'digitalRead' (a nil value)
> if (currentStatusValue != lastStatusValue) {
stdin:1: ')' expected near '!'
> if (digitalRead(statusPin) == HIGH) {
>> client.publish(mqtt_status_topic, "open", true);
>> Serial.println("Door is open! Publishing...");
>> }
>> else if (digitalRead(statusPin) == LOW) {
stdin:5: 'then' expected near 'else'
> client.publish(mqtt_status_topic, "closed", true);
stdin:1: attempt to index global 'client' (a nil value)
> Serial.println("Door is closed! Publishing...");
stdin:1: attempt to index global 'Serial' (a nil value)
> }
stdin:1: unexpected symbol near '}'
> lastStatusValue = currentStatusValue;
> }
stdin:1: unexpected symbol near '}'
> }

stdin:1: unexpected symbol near '}'
> // Function called by callback() when a message is received, passing the message payload as the "requestedAction" parameter
stdin:1: unexpected symbol near '/'
> void triggerDoorAction(String requestedAction) {
stdin:1: '=' expected near 'triggerDoorAction'
> if (requestedAction == "OPEN") {
>> Serial.println("Triggering OPEN relay!");
>> digitalWrite(openPin, HIGH);
>> delay(500);
>> digitalWrite(openPin, LOW);
>> }
>> else if (requestedAction == "CLOSE") {
stdin:7: 'then' expected near 'else'
> Serial.println("Triggering CLOSE relay!");
stdin:1: attempt to index global 'Serial' (a nil value)
> digitalWrite(closePin, HIGH);
stdin:1: attempt to call global 'digitalWrite' (a nil value)
> delay(500);
stdin:1: attempt to call global 'delay' (a nil value)
> digitalWrite(closePin, LOW);
stdin:1: attempt to call global 'digitalWrite' (a nil value)
> }
stdin:1: unexpected symbol near '}'
> else if (requestedAction == "STOP") {
stdin:1: '<eof>' expected near 'else'
> Serial.println("Triggering STOP relay!");
stdin:1: attempt to index global 'Serial' (a nil value)
> digitalWrite(stopPin, HIGH);
stdin:1: attempt to call global 'digitalWrite' (a nil value)
> delay(500);
stdin:1: attempt to call global 'delay' (a nil value)
> digitalWrite(stopPin, LOW);
stdin:1: attempt to call global 'digitalWrite' (a nil value)
> }
stdin:1: unexpected symbol near '}'
> else { Serial.println("Unrecognized action payload... taking no action!");
stdin:1: '<eof>' expected near 'else'
> }
stdin:1: unexpected symbol near '}'
> }

stdin:1: unexpected symbol near '}'
> // Function that runs in loop() to connect/reconnect to the MQTT broker, and publish the current door status on connect
stdin:1: unexpected symbol near '/'
> void reconnect() {
stdin:1: '=' expected near 'reconnect'
> // Loop until we're reconnected
stdin:1: unexpected symbol near '/'
> while (!client.connected()) {
stdin:1: unexpected symbol near '!'
> Serial.print("Attempting MQTT connection...");
stdin:1: attempt to index global 'Serial' (a nil value)
> // Attempt to connect
stdin:1: unexpected symbol near '/'
> if (client.connect(mqtt_clientId, mqtt_username, mqtt_password)) {
>> Serial.println("Connected!");
>> 
>> // Subscribe to the action topic to listen for action messages
stdin:3: unexpected symbol near '/'
> client.subscribe(mqtt_action_topic);
stdin:1: attempt to index global 'client' (a nil value)
> Serial.print("Subscribed to ");
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.print(mqtt_action_topic);
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.println("...");
stdin:1: attempt to index global 'Serial' (a nil value)
> 
> // Publish the current door status on connect/reconnect to ensure HA status is synced with whatever happened while disconnected
stdin:1: unexpected symbol near '/'
> int currentDoorStatus = digitalRead(statusPin);
stdin:1: '=' expected near 'currentDoorStatus'
> if (currentDoorStatus == 0) {
>> Serial.println("Door is closed! Publishing...");
>> client.publish(mqtt_status_topic, "closed", true);
>> }
>> else if (currentDoorStatus == 1) {
stdin:5: 'then' expected near 'else'
> Serial.println("Door is open! Publishing...");
stdin:1: attempt to index global 'Serial' (a nil value)
> client.publish(mqtt_status_topic, "open", true);
stdin:1: attempt to index global 'client' (a nil value)
> }
stdin:1: unexpected symbol near '}'
> }
else {
stdin:1: unexpected symbol near '}'
> Serial.print("failed, rc=");
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.print(client.state());
stdin:1: attempt to index global 'Serial' (a nil value)
> Serial.println(" try again in 5 seconds");
stdin:1: attempt to index global 'Serial' (a nil value)
> // Wait 5 seconds before retrying
stdin:1: unexpected symbol near '/'
> delay(5000);
stdin:1: attempt to call global 'delay' (a nil value)
> }
stdin:1: unexpected symbol near '}'}
}
stdin:1: unexpected symbol near '}'
> 
> void setup() {
stdin:1: '=' expected near 'setup'
> // Setup the output and input pins used in the sketch
stdin:1: unexpected symbol near '/'
> pinMode(openPin, OUTPUT);
stdin:1: attempt to call global 'pinMode' (a nil value)
> digitalWrite(openPin, LOW);
stdin:1: attempt to call global 'digitalWrite' (a nil value)
> 
> pinMode(closePin, OUTPUT);
stdin:1: attempt to call global 'pinMode' (a nil value)
> digitalWrite(closePin, LOW);
stdin:1: attempt to call global 'digitalWrite' (a nil value)
> 
> pinMode(stopPin, OUTPUT);
stdin:1: attempt to call global 'pinMode' (a nil value)
> digitalWrite(stopPin, LOW);
stdin:1: attempt to call global 'digitalWrite' (a nil value)
> 
> pinMode(statusPin, INPUT_PULLUP);
stdin:1: attempt to call global 'pinMode' (a nil value)
> 
> // Setup serial output, connect to wifi, connect to MQTT broker
stdin:1: unexpected symbol near '/'
> Serial.begin(115200);
stdin:1: attempt to index global 'Serial' (a nil value)
> setup_wifi();
stdin:1: attempt to call global 'setup_wifi' (a nil value)
> client.setServer(mqtt_server, 1883);
stdin:1: attempt to index global 'client' (a nil value)
> client.setCallback(callback);
stdin:1: attempt to index global 'client' (a nil value)
> }
stdin:1: unexpected symbol near '}'
> 
> void loop() {
stdin:1: '=' expected near 'loop'
> // Connect/reconnect to the MQTT broker and listen for messages
stdin:1: unexpected symbol near '/'
> if (!client.connected()) {
stdin:1: unexpected symbol near '!'
> reconnect();
stdin:1: attempt to call global 'reconnect' (a nil value)
> }
stdin:1: unexpected symbol near '}'
> client.loop();
stdin:1: attempt to index global 'client' (a nil value)
> 
> // Check door open/closed status each loop and publish changes
stdin:1: unexpected symbol near '/'
> 
> check_door_status();
stdin:1: attempt to call global 'check_door_status' (a nil value)
> }
stdin:1: unexpected symbol near '}'
> 
`

**Comment by marthocoo** [comment]
Hi! Thanks for downloading and trying this out. You'll need to use the Arduino IDE to upload the firmware to the NodeMCU. Download it [here](https://www.arduino.cc/en/Main/Software). Then you'll need to add the ESP8266 board to the IDE, by following the instructions in the "Installing with Boards Manager" section [here](https://github.com/esp8266/Arduino).

After that, open the sketch in the IDE, select the NodeMCU from the Tools --> Board menu, and then select Sketch --> Upload.

Try that and let me know how it works out!

**Comment by onlize** [comment]
I tried it and received this:
`
Arduino: 1.8.3 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

Build options changed, rebuilding all
C:\Users\user\Desktop\Arduino\GarHAge\garHAge.ino\garHAge.ino.ino:4:26: fatal error: PubSubClient.h: No such file or directory

 #include <PubSubClient.h>

                          ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

`

**Comment by marthocoo** [comment]
You will also need to install the PubSubClient library in the Arduino IDE.  Follow the instructions for using the Library Manager [here](https://www.arduino.cc/en/Guide/Libraries#toc3), and search for and install the latest version of PubSubClient.

**Comment by onlize** [comment]
Thank you for your help. I think it did it. At least I did not see any errors.

I have a question about connecting NodeMCU. As far as I can see, this is how I connect it:
Open and close pin is GPIO4 (pin2) and the second connects to the ground.
Sensor for open/close door is connected to GPIO14 (pin5) and the second connects to the ground.

Is that correct?

What is not clear to me is what is Stop pin GPIO5 (pin 8)? Can you please explain where and how I connect it?

Thank you.

**Comment by onlize** [comment]
Oops, my mistake, I guess Open and close pin is GPIO4 (pin2) and connects to relay.

**Comment by marthocoo** [comment]
You are correct about the open/close pin (GPIO4, which on my NodeMCU is D2) and sensor or status pin (GPIO14, which on my NodeMCU is D5).

In my setup, the stop pin (GPIO5, or D1 on my NodeMCU) controls the safety reversing feature on my garage door opener. In the Home Assistant interface, you will have an up arrow, down arrow, and stop button. When my door is closing, I can hit the stop button to cause the door to immediately reverse. You don't have to use it if you'd prefer not to, but then the stop button in the Home Assistant interface will do nothing. 

I run the open/close pin and the stop pin to an input on [this](http://www.robotshop.com/en/2-channel-5v-relay-module.html) dual relay module. I power the NodeMCU via micro USB and so power the relay module from Vin on the NodeMCU (when the NodeMCU is powered via micro USB, the Vin outputs slightly less than 5v but enough to reliably power that relay module). Ground on the relay module runs to one of the NodeMCU ground pins. 

[This](http://www.robotshop.com/en/magnetic-door-switch-set.html) reed switch is what I'm using for the open/close sensor, and its two wires go directly to D5 and ground on my NodeMCU.

**Comment by marthocoo** [comment]
One clarification - that relay module has two inputs, and I use one for the open/close pin and one for the stop pin.

**Comment by onlize** [comment]
The switch and relay that you use is exactly what I have, I assumed that this what I need.

What is the "safety reversing feature on my garage door opener"? How do I know if I have it? I assumed that I needed only power (Vin and Ground) and one of the pins to control relay, but what is this additional pin?

**Comment by marthocoo** [comment]
Many garage door openers (including mine, a Craftsman Liftmaster) implement sensors at the entrance to the garage that will prevent the door from closing or cause it to immediately reverse if the sensors sense something in the path of the door. I have wired the second relay to control this feature so that I can immediately stop the door if I want (more relevant on my door, which is the type that swings outward rather than moving in an up/down plane along the face of the garage). 

If you don't have the sensors at the door, then you don't have this feature and can disregard. If you have them but don't care about this feature, then you can disregard. In both cases, be aware that the stop button in Home Assistant will do nothing.

**Comment by onlize** [comment]
Got it. Thank you very much for your help. I will connect and test this weekend.
